config/routes.rb
Rails.application.routes.draw do
	
	root to: "home#index"
  resources :home do
  	collection do
  		get :blessings
  	end
  end
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :user
end

app/models/current_address.rb
class CurrentAddress < ApplicationRecord
  belongs_to :user
end

app/models/permanent_address.rb
class PermanentAddress < ApplicationRecord
  belongs_to :user
end

app/models/plan.rb
class Plan < ApplicationRecord
	has_many :subscriptions
  has_many :users, through: :subscriptions
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :plan
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :subscriptions
  has_many :bank_accounts
  has_one :permanent_address
  has_one :current_address
  has_many :plans, through: :subscriptions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
  	new_home_path
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!, except: [:index, :blessings]
  def index

  end

  def new
  	
  end

  def blessings
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/blessings.html.erb
<header class="fixed-top">
<div class="container-fluid d-flex top-strip bg-light p-0 pl-3 pr-3">
  <ul class="clearfix ml-auto">
      <li class="float-left mr-4"><i class="fas fa-phone-alt mr-1 text-secondary"></i><a href="#" class="text-dark">9822368492</a></li>
      <li class="float-left"><i class="fas fa-envelope mr-1 text-secondary"></i><a href="#" class="text-dark">info@example.com</a></li>
  </ul>
</div>
<nav class="navbar navbar-expand-md navbar-light bg-white shadow py-2 pl-4 pr-4">
    <img class="navbar-brand mr-auto logo" src=<%=asset_path('ArjunParvatilogo.svg')%> style="width:334px;height:85px;" />
      <div class="nav-menu">
        
        <form class="form-inline mt-2 mt-md-0 mr-4">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                <li class="nav-item mr-2 active">
                  <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item mr-2">
                   <%= link_to "Blessings", blessings_home_index_path,class: "nav-link", :method => :get %>
                </li>
                <li class="nav-item mr-2 pr-4">
                  <a class="nav-link" href="#">Pricing</a>
                </li>
                <li class="nav-item rounded bg-dark loginBtn mr-3">
                  <%= link_to "Sign in", new_user_session_path,class: "nav-link text-white", :method => :get %>
                </li>
                <li class="nav-item rounded bg-danger signUpBtn">
                  <%= link_to "Sign Up", new_user_registration_path,class: "nav-link text-white", :method => :get %>
                </li>
              </ul>
            </div>
        </form>
      </div>
    </nav>

</header>


<div class="container-fluid">
  <div class="row vh-100 bg-white">
    <div class="col-md-5 d-flex">
      <div class="blessing-wrapper m-auto">
        <div class="brand-wrapper mb-5">
        </div>
        <p class="blessing-text text-danger animate__animated animate__fadeInDown">
          <span style="position: relative;top: -27px;">&#8220;</span>The loss of my father will always sting. But now, everything that I do is in honor of him and celebrates his life.<span style="position: relative;top: -17px;">&#8221;</span></br>
        </p>
        <div class="ml-auto clearfix animate__animated animate__zoomIn">
          <img class="float-right" style="width: 300px;text-align: right;" alt="signature" src=<%=asset_path('signature.png')%> />
        </div>
      </div>
    </div>
    <div class="col-md-7 px-0 d-none d-md-block">
         <!-- <div class="blessing-bg"></div> -->
  <img class="mr-auto blessing-bg  animate__animated animate__zoomIn"  style ="
    width: 100%;" alt="login image" src=<%=asset_path('Anna_image.png')%> /> 
    </div>
  </div>
</div>

<script>
  $(document).ready(function () {
    $("#new_user").validate({
      rules: {
        "user[email]": {
            email: true,
            required: true
        },
        "user[password]": {
          required: true
        }
      },
      messages: {
        "user[email]": {
          required: "Email can not be blank"
        },
        "user[password]": {
          required: "Password can not be blank"
        },
      },
      errorPlacement: function (error, element) {
        var name = $(element).attr("name");
        var error_element = name.match(/\[(.*?)\]/)[1]+"_error";
        error.appendTo($("#email_error"));
        if ( error_element == "email_error") {
          error.appendTo("#email_error");
        } else {
          error.appendTo("#password_error");
        }
      },
    });
  });
</script>
<style>
.blessing-text {
  font-family: 'ReginaScript';
  font-size: 3rem;
  padding-left: 0px;
  color: crimson !important;
}
.blessing-bg {
  width: 100%;
  padding: 0px 0px 0 384px;
  height: calc( 100vh - 143px);
  position: relative;
  top: 142px;
}
.blessing-wrapper {
  width: 100%;
  max-width: 100%;
  padding: 34px;
  border-radius: 8px;
  border: 0;
  background-color: #fff; 
}

:root{
    --animate-duration:1s;
    --animate-delay:1s;
    --animate-repeat:1
}
.animate__animated{
    -webkit-animation-duration:1s;
    animation-duration:1s;
    -webkit-animation-duration:var(--animate-duration);
    animation-duration:var(--animate-duration);
    -webkit-animation-fill-mode:both;
    animation-fill-mode:both
}
@-webkit-keyframes zoomIn{
    0%{
        opacity:0;
        -webkit-transform:scale3d(.3,.3,.3);
        transform:scale3d(.3,.3,.3)
    }
    50%{
        opacity:1
    }
}
@keyframes zoomIn{
    0%{
        opacity:0;
        -webkit-transform:scale3d(.3,.3,.3);
        transform:scale3d(.3,.3,.3)
    }
    50%{
        opacity:1
    }
}
.animate__zoomIn{
    -webkit-animation-name:zoomIn;
    animation-name:zoomIn
}

@-webkit-keyframes fadeInDown{
    0%{
        opacity:0;
        -webkit-transform:translate3d(0,-100%,0);
        transform:translate3d(0,-100%,0)
    }
    to{
        opacity:1;
        -webkit-transform:translateZ(0);
        transform:translateZ(0)
    }
}
@keyframes fadeInDown{
    0%{
        opacity:0;
        -webkit-transform:translate3d(0,-100%,0);
        transform:translate3d(0,-100%,0)
    }
    to{
        opacity:1;
        -webkit-transform:translateZ(0);
        transform:translateZ(0)
    }
}
.animate__fadeInDown{
    -webkit-animation-name:fadeInDown;
    animation-name:fadeInDown
}
</style>

app/views/home/index.html.erb
<header class="fixed-top">
<div class="container-fluid d-flex top-strip bg-light p-0 pl-4 pr-4">
  <ul class="clearfix ml-auto">
      <li class="float-left mr-4"><i class="fas fa-phone-alt mr-1 text-secondary"></i><a href="#" class="text-dark">9822368492</a></li>
      <li class="float-left"><i class="fas fa-envelope mr-1 text-secondary"></i><a href="#" class="text-dark">info@example.com</a></li>
  </ul>
</div>
<nav class="navbar navbar-expand-md navbar-light bg-white shadow py-2 pl-4 pr-4">
    <img class="navbar-brand mr-auto logo" src=<%=asset_path('ArjunParvatilogo.svg')%> style="width:334px;height:85px;" />
      <div class="nav-menu">
        
        <form class="form-inline mt-2 mt-md-0">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                <li class="nav-item mr-2 active">
                  <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item mr-2">
                   <%= link_to "Blessings", blessings_home_index_path,class: "nav-link", :method => :get %>
                </li>
                <li class="nav-item mr-2 pr-4">
                  <a class="nav-link" href="#">Pricing</a>
                </li>
                <li class="nav-item rounded bg-dark loginBtn mr-3">
                  <%= link_to "Sign in", new_user_session_path,class: "nav-link text-white", :method => :get %>
                </li>
                <li class="nav-item rounded bg-danger signUpBtn">
                  <%= link_to "Sign Up", new_user_registration_path,class: "nav-link text-white", :method => :get %>
                </li>
              </ul>
            </div>
        </form>
      </div>
    </nav>

</header>

<main role="main" class="pl-0 pr-0 pb-0 container-fluid">
<div class="home-banner p-0">
</div>

<div class="container-fluid p-0 pt-0">

    <div class="container-fluid pt-5 pb-5">
    <h1 class="d-flex justify-content-center">Why Choose Us</h1>
    <p class="d-flex justify-content-center">With the values, we embrace our mission to bring each investor the best service</p>
    </div>
    <div class="row pb-5">
        <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
            <div class="d-flex justify-content-center">
            <p><img class="" src=<%=asset_path('icon1.png')%> /></p>
            </div>
            <div class="d-flex justify-content-center">
              <h3 class="pt-3 pb-3">Experienced</h3>
            </div>
            <div class="d-flex justify-content-center pl-5 pr-5">
            <p class="">Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown.</p>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
            <div class="d-flex justify-content-center">
            <p><img class="" src=<%=asset_path('icon2.png')%> /></p>
            </div>
            <div class="d-flex justify-content-center">
              <h3 class="pt-3 pb-3">Investment Agreement</h3>
            </div>
            <div class="d-flex justify-content-center pl-5 pr-5">
            <p class="">Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown.</p>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
            <div class="d-flex justify-content-center">
            <p><img class="" src=<%=asset_path('icon3.png')%> /></p>
            </div>
            <div class="d-flex justify-content-center">
              <h3 class="pt-3 pb-3">Rewards</h3>
            </div>
            <div class="d-flex justify-content-center pl-5 pr-5">
            <p class="">Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown.</p>
            </div>
        </div>
    </div>


    <div class="home-banner1 p-0">
        <h1 class="d-flex justify-content-center pb-4">What Our Investor Say</h1>
        <div class="d-flex justify-content-center">
          <p><img class="" src=<%=asset_path('mayur.png')%> /></p>
        </div>
        <div class="d-flex justify-content-center pl-5 pr-5">
        <h2 class="pt-3 pb-3">Mayur Patil - Prime Investor</h2>
        </div>
        <div class="d-flex justify-content-center pl-5 pr-5">
        <p class="">Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown.</p>
        </div>
    </div>



    <div class="container-fluid pt-5 pb-5">
    <h1 class="d-flex justify-content-center">Help Simplify Your Finance</h1>
    <p class="d-flex justify-content-center">Let us spend time take care of your finance and you spend time enjoy your life</p>
    </div>
    <div class="row pb-5">
        <div class="col-sm-12 col-md-6 col-lg-3 col-xl-3">            
            <div class="d-flex justify-content-center">
              <h2 class="pt-3 pb-1">125</h2>
            </div>
            <div class="d-flex justify-content-center pl-5 pr-5">
            <p class="">Employees</p>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-3 col-xl-3">
            <div class="d-flex justify-content-center">
              <h2 class="pt-3 pb-1">100</h2>
            </div>
            <div class="d-flex justify-content-center pl-5 pr-5">
            <p class="">% Satisfication</p>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-3 col-xl-3">
            <div class="d-flex justify-content-center">
              <h2 class="pt-3 pb-1">9192</h2>
            </div>
            <div class="d-flex justify-content-center pl-5 pr-5">
            <p class="">Coffee Cups</p>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-3 col-xl-3">
        <div class="d-flex justify-content-center">
          <h2 class="pt-3 pb-1">9.5</h2>
        </div>
        <div class="d-flex justify-content-center pl-5 pr-5">
        <p class="">Rating</p>
        </div>
    </div>
    </div>


    <div class="home-banner2 p-0">
      <div class="d-flex justify-content-center">
      <button type="button" class="btn btn-lg btn-warning font-weight-bold text-dark">Start Your Investment</button>
      </div>   
    </div>




</div>

</main>

<footer id="footer">
  <div class="container-fluid p-0">
  <div class="footer-top">
    <div class="container-fluid">
      <div class="row">

        <div class="col-lg-3 col-md-6 footer-info">
          <h3>Company Name</h3>
          <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus. Scelerisque felis imperdiet proin fermentum leo. Amet volutpat consequat mauris nunc congue.</p>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><i class="fas fa-chevron-right"></i> <a href="#">Home</a></li>
            <li><i class="fas fa-chevron-right"></i> <a href="#">About us</a></li>
            <li><i class="fas fa-chevron-right"></i> <a href="#">Services</a></li>
            <li><i class="fas fa-chevron-right"></i> <a href="#">Terms of service</a></li>
            <li><i class="fas fa-chevron-right"></i> <a href="#">Privacy policy</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-6 footer-contact">
          <h4>Contact Us</h4>
          <p>
            A108 Adam Street <br>
            New York, NY 535022<br>
            United States <br>
          <strong>Phone:</strong> +1 5589 55488 55<br>
          <strong>Email:</strong> info@example.com<br>
        </p>

        <div class="social-links">
          <a href="#" class="twitter"><i class="fab fa-twitter"></i></a>
          <a href="#" class="facebook"><i class="fab fa-facebook"></i></a>
          <a href="#" class="instagram"><i class="fab fa-instagram"></i></a>
          <a href="#" class="linkedin"><i class="fab fa-linkedin"></i></a>
        </div>

      </div>

      <div class="col-lg-3 col-md-6 footer-newsletter">
        <h4>Our Newsletter</h4>
        <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna veniam enim veniam illum dolore legam minim quorum culpa amet magna export quem marada parida nodela caramase seza.</p>
        <form action="" method="post">
          <input type="email" name="email"><input type="submit" value="Subscribe">
        </form>
      </div>

    </div>
  </div>
</div>  

<div class="container-fluid p-0">
      <div class="copyright">
      &copy; Copyright <strong>Company Name</strong>. All Rights Reserved
      </div>
    </div>

  </div>
</footer>
<!-- Home page Ends -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArjunParvatiSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <div class="main-wrapper">
  <div class="wrapper">
    <% unless flash.empty? %>
      <script type="text/javascript">
          <% flash.each do |f| %>
        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
         toastr['<%= type %>']('<%= f[1] %>');
       <% end %>
      </script>
    <% end %>
    <%= yield %>
    </div>
    </div>
  </body>
</html>